spring:
  kafka:
    bootstrap-servers: localhost:9092
    group-id: ws
  jackson:
    default-property-inclusion: non_null
    serialization.FAIL_ON_EMPTY_BEANS: false
server:
  port: 9082

logging:
#  level.root: DEBUG
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'